service: dockerfarm-api # NOTE: update this with your service name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
#  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs6.10
  environment: 
    NODE_ENV: ${opt:stage}
functions:
  app:
    handler: src/serverless.handler 
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    cors:
      origin: '*' 
      
